Section	"Device"
	Identifier	"Intel Graphics"
        Driver		"modesetting"
        #Option		"DRI"			"2"
        #Option		"AccelMethod"		"uxa"
	Option		"TearFree"		"false"
	Option		"TripleBuffer"		"false"
	Option		"SwapbuffersWait"	"false"
EndSection
