# vim: ft=confini
[Autologin]
Relogin=true
Session=plasma
User=user

[General]
DisplayServer=wayland
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=breeze

[Users]
MaximumUid=60513
MinimumUid=1000
