# server_names = []
# disabled_server_names = []
# listen_addresses = [] # systemd socket
listen_addresses = ['127.0.0.1:53', '[::1]:53'] # systemd service
block_ipv6 = false
block_undelegated = true
block_unqualified = true
ipv4_servers = true
ipv6_servers = true
dnscrypt_servers = true
doh_servers = false
odoh_servers = true
require_dnssec = true
require_nofilter = true
require_nolog = false
bootstrap_resolvers = ['8.8.8.8:53', '1.1.1.1:53']
cache = true
http3 = false
ignore_system_dns = true
lb_estimator = true
netprobe_address = '8.8.8.8:53'
netprobe_timeout = -1
use_syslog = true

[local_doh]
listen_addresses = ['127.0.0.1:3000', '[::1]:3000']
path = '/dns-query'
cert_file = "/etc/dnscrypt-proxy/localhost.pem"
cert_key_file = "/etc/dnscrypt-proxy/localhost.pem"

[sources]
  [sources.public-resolvers]
    urls = ['https://cdn.jsdelivr.net/gh/DNSCrypt/dnscrypt-resolvers@master/v3/public-resolvers.md', 'https://cdn.statically.io/gh/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md']
    cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    refresh_delay = 72
    prefix = ''

  [sources.relays]
    urls = ['https://cdn.jsdelivr.net/gh/DNSCrypt/dnscrypt-resolvers@master/v3/relays.md', 'https://cdn.statically.io/gh/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md', 'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md', 'https://download.dnscrypt.info/resolvers-list/v3/relays.md']
    cache_file = '/var/cache/dnscrypt-proxy/relays.md'
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    refresh_delay = 72
    prefix = ''

  [sources.odoh-servers]
    urls = ['https://cdn.jsdelivr.net/gh/DNSCrypt/dnscrypt-resolvers@master/v3/odoh-servers.md', 'https://cdn.statically.io/gh/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-servers.md', 'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-servers.md', 'https://download.dnscrypt.info/resolvers-list/v3/odoh-servers.md']
    cache_file = '/var/cache/dnscrypt-proxy/odoh-servers.md'
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    refresh_delay = 24
    prefix = ''

  [sources.odoh-relays]
    urls = ['https://cdn.jsdelivr.net/gh/DNSCrypt/dnscrypt-resolvers@master/v3/odoh-relays.md', 'https://cdn.statically.io/gh/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-relays.md', 'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-relays.md', 'https://download.dnscrypt.info/resolvers-list/v3/odoh-relays.md']
    cache_file = '/var/cache/dnscrypt-proxy/odoh-relays.md'
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    refresh_delay = 24
    prefix = ''

[broken_implementations]
fragments_blocked = ['cisco', 'cisco-ipv6', 'cisco-familyshield', 'cisco-familyshield-ipv6', 'cleanbrowsing-adult', 'cleanbrowsing-adult-ipv6', 'cleanbrowsing-family', 'cleanbrowsing-family-ipv6', 'cleanbrowsing-security', 'cleanbrowsing-security-ipv6']

[anonymized_dns]
routes = [
   { server_name='*', via=['*'] }
]
skip_incompatible = false
direct_cert_fallback = true

[dns64]
# prefix = ['64:ff9b::/96']
# resolver = ['[2606:4700:4700::64]:53', '[2606:4700:4700::6400]:53', '[2001:4860:4860::64]:53', '[2001:4860:4860::6464]:53']

[static]
  # [static.myserver]
  #   stamp = 'sdns://AQcAAAAAAAAAAAAQMi5kbnNjcnlwdC1jZXJ0Lg'
